### ISSUE TITLE
Benchmark Numbers

### ISSUE THREAD

**Issue by Aaronontheweb** [Aaronontheweb/FastAtomicLazy#5]
Following merging of #4, here's what I get on my Ryzen machine at home:

```
BenchmarkDotNet=v0.10.14, OS=Windows 10.0.17134
AMD Ryzen 7 1700 Eight-Core Processor, 1 CPU, 16 logical and 8 physical cores
  [Host]   : .NET Framework 4.6.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3110.0  [AttachedDebugger]
  Core 2.0 : .NET Core 2.0.7 (CoreCLR 4.6.26328.01, CoreFX 4.6.26403.03), 64bit RyuJIT
  Core 2.1 : .NET Core 2.1.0 (CoreCLR 4.6.26515.07, CoreFX 4.6.26515.06), 64bit RyuJIT
  Desktop  : .NET Framework 4.6.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3110.0
```

|                           Method |      Job | Runtime |     Toolchain |      Mean |     Error |    StdDev |
|--------------------------------- |--------- |-------- |-------------- |----------:|----------:|----------:|
|                     ReadFastLazy | Core 2.0 |    Core | .NET Core 2.0 | 1.4939 ns | 0.0514 ns | 0.0456 ns |
|            ReadLazyNotThreadSafe | Core 2.0 |    Core | .NET Core 2.0 | 0.2834 ns | 0.0074 ns | 0.0058 ns |
|    ReadLazyPublishOnlyThreadSafe | Core 2.0 |    Core | .NET Core 2.0 | 0.2671 ns | 0.0382 ns | 0.0455 ns |
| ReadLazyReadAndExecuteThreadSafe | Core 2.0 |    Core | .NET Core 2.0 | 0.2990 ns | 0.0402 ns | 0.0550 ns |
|                     ReadFastLazy | Core 2.1 |    Core | .NET Core 2.1 | 1.5876 ns | 0.0696 ns | 0.0581 ns |
|            ReadLazyNotThreadSafe | Core 2.1 |    Core | .NET Core 2.1 | 0.3010 ns | 0.0428 ns | 0.0458 ns |
|    ReadLazyPublishOnlyThreadSafe | Core 2.1 |    Core | .NET Core 2.1 | 0.3060 ns | 0.0471 ns | 0.0504 ns |
| ReadLazyReadAndExecuteThreadSafe | Core 2.1 |    Core | .NET Core 2.1 | 0.3377 ns | 0.0470 ns | 0.0462 ns |
|                     ReadFastLazy |  Desktop |     Clr |       Default | 1.1573 ns | 0.0533 ns | 0.0473 ns |
|            ReadLazyNotThreadSafe |  Desktop |     Clr |       Default | 2.4837 ns | 0.0161 ns | 0.0126 ns |
|    ReadLazyPublishOnlyThreadSafe |  Desktop |     Clr |       Default | 2.5683 ns | 0.0906 ns | 0.0848 ns |
| ReadLazyReadAndExecuteThreadSafe |  Desktop |     Clr |       Default | 2.0452 ns | 0.0763 ns | 0.0848 ns |

**Comment by Aaronontheweb** [comment]
After merging in #3 

// * Summary *

BenchmarkDotNet=v0.10.14, OS=Windows 10.0.17134
AMD Ryzen 7 1700 Eight-Core Processor, 1 CPU, 16 logical and 8 physical cores
  [Host]   : .NET Framework 4.6.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3110.0
  Core 2.0 : .NET Core 2.0.7 (CoreCLR 4.6.26328.01, CoreFX 4.6.26403.03), 64bit RyuJIT
  Core 2.1 : .NET Core 2.1.0 (CoreCLR 4.6.26515.07, CoreFX 4.6.26515.06), 64bit RyuJIT
  Desktop  : .NET Framework 4.6.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3110.0


                           Method |      Job | Runtime |     Toolchain |      Mean |     Error |
 StdDev |
--------------------------------- |--------- |-------- |-------------- |----------:|----------:|----------:|
                     ReadFastLazy | Core 2.0 |    Core | .NET Core 2.0 | 1.2712 ns | 0.0505 ns | 0.0448 ns |
            ReadLazyNotThreadSafe | Core 2.0 |    Core | .NET Core 2.0 | 0.3066 ns | 0.0119 ns | 0.0093 ns |
    ReadLazyPublishOnlyThreadSafe | Core 2.0 |    Core | .NET Core 2.0 | 0.3236 ns | 0.0239 ns | 0.0200 ns |
 ReadLazyReadAndExecuteThreadSafe | Core 2.0 |    Core | .NET Core 2.0 | 0.3366 ns | 0.0421 ns | 0.0394 ns |
                     ReadFastLazy | Core 2.1 |    Core | .NET Core 2.1 | 1.2817 ns | 0.0575 ns | 0.0538 ns |
            ReadLazyNotThreadSafe | Core 2.1 |    Core | .NET Core 2.1 | 0.3005 ns | 0.0483 ns | 0.0645 ns |
    ReadLazyPublishOnlyThreadSafe | Core 2.1 |    Core | .NET Core 2.1 | 0.3165 ns | 0.0443 ns | 0.0474 ns |
 ReadLazyReadAndExecuteThreadSafe | Core 2.1 |    Core | .NET Core 2.1 | 0.3289 ns | 0.0351 ns | 0.0328 ns |
                     ReadFastLazy |  Desktop |     Clr |       Default | 1.3444 ns | 0.0594 ns | 0.0556 ns |
            ReadLazyNotThreadSafe |  Desktop |     Clr |       Default | 2.5151 ns | 0.0710 ns | 0.0592 ns |
    ReadLazyPublishOnlyThreadSafe |  Desktop |     Clr |       Default | 2.0768 ns | 0.0682 ns | 0.0701 ns |
 ReadLazyReadAndExecuteThreadSafe |  Desktop |     Clr |       Default | 1.9805 ns | 0.0547 ns | 0.0427 ns |

**Comment by Aaronontheweb** [comment]
Updated Benchmark Numbers

## .NET 5

``` ini

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19041.1110 (2004/May2020Update/20H1)
AMD Ryzen 7 1700, 1 CPU, 16 logical and 8 physical cores
.NET SDK=5.0.302
  [Host]     : .NET 5.0.8 (5.0.821.31504), X64 RyuJIT
  DefaultJob : .NET 5.0.8 (5.0.821.31504), X64 RyuJIT


```
|                           Method |      Mean |     Error |    StdDev | Allocated |
|--------------------------------- |----------:|----------:|----------:|----------:|
|                     ReadFastLazy | 1.1824 ns | 0.0077 ns | 0.0064 ns |         - |
|            ReadLazyNotThreadSafe | 0.3161 ns | 0.0047 ns | 0.0041 ns |         - |
|    ReadLazyPublishOnlyThreadSafe | 0.3198 ns | 0.0116 ns | 0.0097 ns |         - |
| ReadLazyReadAndExecuteThreadSafe | 0.3081 ns | 0.0051 ns | 0.0045 ns |         - |

## .NET Core 3.1

``` ini

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19041.1110 (2004/May2020Update/20H1)
AMD Ryzen 7 1700, 1 CPU, 16 logical and 8 physical cores
.NET SDK=5.0.302
  [Host]     : .NET Core 3.1.17 (CoreCLR 4.700.21.31506, CoreFX 4.700.21.31502), X64 RyuJIT
  DefaultJob : .NET Core 3.1.17 (CoreCLR 4.700.21.31506, CoreFX 4.700.21.31502), X64 RyuJIT


```
|                           Method |      Mean |     Error |    StdDev | Allocated |
|--------------------------------- |----------:|----------:|----------:|----------:|
|                     ReadFastLazy | 1.6049 ns | 0.0104 ns | 0.0081 ns |         - |
|            ReadLazyNotThreadSafe | 0.3216 ns | 0.0122 ns | 0.0102 ns |         - |
|    ReadLazyPublishOnlyThreadSafe | 0.3062 ns | 0.0081 ns | 0.0068 ns |         - |
| ReadLazyReadAndExecuteThreadSafe | 0.3212 ns | 0.0073 ns | 0.0064 ns |         - |


## .NET Framework 4.8

``` ini

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19041.1110 (2004/May2020Update/20H1)
AMD Ryzen 7 1700, 1 CPU, 16 logical and 8 physical cores
  [Host]     : .NET Framework 4.8 (4.8.4390.0), X64 RyuJIT
  DefaultJob : .NET Framework 4.8 (4.8.4390.0), X64 RyuJIT


```
|                           Method |     Mean |     Error |    StdDev | Allocated |
|--------------------------------- |---------:|----------:|----------:|----------:|
|                     ReadFastLazy | 1.425 ns | 0.0222 ns | 0.0197 ns |         - |
|            ReadLazyNotThreadSafe | 2.390 ns | 0.0383 ns | 0.0339 ns |         - |
|    ReadLazyPublishOnlyThreadSafe | 2.395 ns | 0.0352 ns | 0.0312 ns |         - |
| ReadLazyReadAndExecuteThreadSafe | 2.422 ns | 0.0588 ns | 0.0521 ns |         - |

**Comment by F0b0s** [comment]
@Aaronontheweb as i got it, the main purpose of this library was non blocking(i.e. without using lock keyword) call factory method. But benchmark measures `Value` method which in my opinion the same in both implementation because factory was called only once:
[FastAtomicLazy](https://github.com/Aaronontheweb/FastAtomicLazy)
```
public T Value
        {
            get
            {
                if (IsValueCreated)
                    return _createdValue;
```
Microsoft Lazy:
`        public T Value => _state == null ? _value! : CreateValue();`

The both have only one volatile read operation. I tried to run benchmark multiplpe times in different order and it shows me different results:

**.NET 5.0.12** 
BenchmarkDotNet=v0.13.1, OS=macOS Monterey 12.5.1 (21G83) [Darwin 21.6.0]
Apple M1 2.40GHz, 1 CPU, 8 logical and 8 physical cores
.NET SDK=7.0.101
  [Host]     : .NET 5.0.12 (5.0.1221.52207), X64 RyuJIT
  DefaultJob : .NET 5.0.12 (5.0.1221.52207), X64 RyuJIT


|                           Method |      Mean |     Error |    StdDev | Allocated |
|--------------------------------- |----------:|----------:|----------:|----------:|
| ReadLazyReadAndExecuteThreadSafe | 0.1869 ns | 0.0025 ns | 0.0019 ns |         - |
|            ReadLazyNotThreadSafe | 3.4458 ns | 0.0165 ns | 0.0138 ns |         - |
|    ReadLazyPublishOnlyThreadSafe | 0.2760 ns | 0.0194 ns | 0.0172 ns |         - |
|                     ReadFastLazy | 0.9587 ns | 0.0020 ns | 0.0017 ns |         - |

|                           Method |       Mean |     Error |    StdDev | Allocated |
|--------------------------------- |-----------:|----------:|----------:|----------:|
| ReadLazyReadAndExecuteThreadSafe |  0.0000 ns | 0.0000 ns | 0.0000 ns |         - |
|            ReadLazyNotThreadSafe |  0.2047 ns | 0.0021 ns | 0.0016 ns |         - |
|    ReadLazyPublishOnlyThreadSafe |  0.3576 ns | 0.0013 ns | 0.0011 ns |         - |
|                     ReadFastLazy | 11.0374 ns | 0.0337 ns | 0.0299 ns |         - |

|                           Method |      Mean |     Error |    StdDev | Allocated |
|--------------------------------- |----------:|----------:|----------:|----------:|
|                     ReadFastLazy | 0.4848 ns | 0.0130 ns | 0.0109 ns |         - |
|            ReadLazyNotThreadSafe | 0.1859 ns | 0.0019 ns | 0.0017 ns |         - |
|    ReadLazyPublishOnlyThreadSafe | 0.2697 ns | 0.0029 ns | 0.0026 ns |         - |
| ReadLazyReadAndExecuteThreadSafe | 0.0000 ns | 0.0000 ns | 0.0000 ns |         - |

|                           Method |      Mean |     Error |    StdDev | Allocated |
|--------------------------------- |----------:|----------:|----------:|----------:|
|                     ReadFastLazy | 0.4712 ns | 0.0021 ns | 0.0017 ns |         - |
|            ReadLazyNotThreadSafe | 0.0000 ns | 0.0000 ns | 0.0000 ns |         - |
|    ReadLazyPublishOnlyThreadSafe | 0.9377 ns | 0.0217 ns | 0.0193 ns |         - |
| ReadLazyReadAndExecuteThreadSafe | 0.1259 ns | 0.0207 ns | 0.0194 ns |         - |

I think this benchmark is not correct, because we need to measure factory method in concurrent environment.

Also, you can see problems with this benchmark for `ReadLazyNotThreadSafe` and `ReadLazyReadAndExecuteThreadSafe` positions, it's always has different results, but if you compare implementation
ReadLazyNotThreadSafe:
```
        public Lazy(Func<T> valueFactory)
            : this(valueFactory, LazyThreadSafetyMode.ExecutionAndPublication, useDefaultConstructor: false)
        {
        }
```
ReadLazyReadAndExecuteThreadSafe

```
_readAndExecuteSafeLazy = new Lazy<int>(() => new Random().Next(), LazyThreadSafetyMode.ExecutionAndPublication);

public Lazy(Func<T> valueFactory, LazyThreadSafetyMode mode)
            : this(valueFactory, mode, useDefaultConstructor: false)
        {
        }
```


it's completely the same.

**Comment by F0b0s** [comment]
Also i fixed unsafeLazy benchmark, please review it.

**Comment by Aaronontheweb** [comment]
> Also i fixed unsafeLazy benchmark, please review it.

will do
